[General]
	#
	############################################
	#
	#Default: false
	#-------------------------------------------
	"Boolean: Debug Mode" = false

[Debug]
	#
	############################################
	#
	#Default: false
	#-------------------------------------------
	"Boolean: Show Buttons Pressed" = false

[Controller]
	#
	############################################
	#This prevents the mod from restricting you from changing what model the mod sees your controller as
	#-------------------------------------------
	#Default: false
	#-------------------------------------------
	"Boolean: Use Any Model" = false
	#
	############################################
	#The sensitivity of the controller ingame
	#-------------------------------------------
	#Default: 0.5
	#-------------------------------------------
	#Range: 0.0 ~ 1.0
	"Float: Ingame Sensitivity" = 0.5
	#
	############################################
	#The sensitivity of the controller in the menu
	#-------------------------------------------
	#Default: 0.2
	#-------------------------------------------
	#Range: 0.0 ~ 1.0
	"Float: Menu Sensitivity" = 0.2
	#
	############################################
	#Allows you to use mose fine movements using your thumbstick
	#-------------------------------------------
	#Default: true
	#-------------------------------------------
	"Boolean: Use Precise Movement" = true

[Gameplay]
	#
	############################################
	#Shows your name on the to right of the screen when in multiplayer
	#Useful in split-screen to identify whose instance is whose
	#-------------------------------------------
	#Default: true
	#-------------------------------------------
	"Boolean: Show Ingame Player Names" = true
	#
	############################################
	#Shows your current coordinates on the screen if you are allowed to see them
	#I hope you weren't planning to use this feature to bypass the reduced debug info rule
	#-------------------------------------------
	#Default: false
	#-------------------------------------------
	"Boolean: Show Coordinates" = false
	#
	############################################
	#Allows you to determine the safe area of your screen
	#This only works ingame. Any elements in any other menus will not be moved
	#-------------------------------------------
	#Default: 100.0
	#-------------------------------------------
	#Range: 0.0 ~ 100.0
	"Float: Safe Area" = 100.0
	#
	############################################
	#SHows button hints at the bottom right and left of your screen
	#-------------------------------------------
	#Default: false
	#-------------------------------------------
	"Boolean: Show Button Hints" = false
	#
	############################################
	#Shows the mini you at the top left corner of the screen
	#Adorable right?
	#-------------------------------------------
	#Default: true
	#-------------------------------------------
	"Boolean: Show Paper Doll" = false

[Deadzone]
	#
	############################################
	#The deadzone of the controller during general use
	#-------------------------------------------
	#Default: 0.2
	#-------------------------------------------
	#Range: 0.0 ~ 1.0
	"Float: General" = 0.2
	#
	############################################
	#The deadzone of the controller while using the on-screen keyboard
	#-------------------------------------------
	#Default: 0.7
	#-------------------------------------------
	#Range: 0.0 ~ 1.0
	"Float: On-Screen Keyboard" = 0.7
