#Configure the delays related to the healing of explosions.
[delays]
	#(Default = 3.0) How much time in seconds should an explosion wait for to begin healing.
	explosion_heal_delay = 3.0
	#(Default = 1.0) The time in seconds that a block takes to heal.
	block_placement_delay = 1.0

#Toggle whether certain explosion should drop items. Does not include items stored in container blocks.
[explosion_item_drops]
	#(Default = false) Whether to drop items on explosions caused by mobs such as Creepers.
	drop_items_on_mob_explosions = false
	#(Default = true) Whether to drop items on explosions caused by blocks such as beds or end crystal blocks.
	drop_items_on_block_explosions = true
	#(Default = true) Whether to drop items on explosions caused by TNT blocks and TNT minecarts.
	drop_items_on_tnt_explosions = true
	#(Default = true) Whether to drop items on explosions such as those caused by wind bursts.
	drop_items_on_triggered_explosions = true
	#(Default = true) Whether to drop items on explosions whose source is not any of the ones provided in this setting category.
	drop_items_on_other_explosions = true
	#Add mob identifiers to this blacklist to prevent explosions caused by the added mobs from dropping items if drop_items_on_mob_explosions is enabled.
	drop_items_on_mob_explosions_blacklist = ["minecraft:placeholder"]

#Configure which explosions are allowed to heal.
[explosion_sources]
	#(Default = true) Heal explosions caused by mobs such as Creepers.
	heal_mob_explosions = true
	#(Default = false) Heal explosions caused by blocks such as beds or end crystal blocks.
	heal_block_explosions = false
	#(Default = false) Heal explosions caused by TNT blocks and TNT minecarts.
	heal_tnt_explosions = false
	#(Default = false) Heal explosions such as those caused by wind bursts.
	heal_triggered_explosions = false
	#(Default = false) Heal explosions caused by sources which aren't any of the ones provided in this setting category.
	heal_other_explosions = false
	#Add mob identifiers to this blacklist to prevent explosions caused by the added mobs from healing if heal_mob_explosions is enabled.
	heal_mob_explosions_blacklist = ["minecraft:placeholder"]

#Choose between different special modes for explosion healing. Note that certain healing modes will not follow the explosion delay and block delay settings.
[explosion_healing_mode]
	#(Default = "default_mode") Choose any of the following healing modes by copying one of the strings and pasting it into the value of the "mode" setting below:
	#"default_mode", "daytime_healing_mode", "difficulty_based_healing_mode", "blast_resistance_based_healing_mode"
	mode = "DEFAULT_MODE"

#Toggleable settings for extra features.
[preferences]
	#(Default = false) Whether to restore block nbt data upon healing. This option prevents container blocks like chests from dropping their inventories. Does not apply when the healed block is different from the destroyed block due to a replace map entry.
	restore_block_nbt = false
	#(Default = false) Whether to force blocks with nbt data to always heal, even if the replace map specifies a replacement for that block, and regardless of the block that may be occupying that position at the moment of healing.
	force_blocks_with_nbt_to_always_heal = false
	#(Default = true) Allows for a falling block, like sand or gravel, to fall when healed. Disabling this option makes the falling block have to receive a neighbor update before falling.
	make_falling_blocks_fall = true
	#(Default = true) Whether a block placement sound effect should be played when a block is healed.
	block_placement_sound_effect = true
	#(Default = true) Whether a block placement sound effect should produce some cloud particles.
	block_placement_particles = true
	#(Default = true) Makes explosion heal immediately when a potion of Healing is thrown on them.
	heal_on_healing_potion_splash = true
	#(Default = true) Makes explosions begin their healing process when a potion of Regeneration is thrown on them.
	heal_on_regeneration_potion_splash = true
	#(Default = false) Toggle the usage of the whitelist.
	enable_whitelist = false

#Use an optional whitelist to customize which blocks are allowed to heal. To add an entry, specify the block's namespace
#along with its identifier, separated by a colon and enclosed in double quotes, and add it in-between the square brackets below. Separate each entry with a comma.
#Example entries:
#whitelist_entries = ["minecraft:grass",  "minecraft:stone", "minecraft:sand"]
[whitelist]
	whitelist = ["minecraft:placeholder"]

#Add your own replace entries to configure which blocks should be used to heal other blocks. The block on the right will be used to heal the block on the left.
#Specify the block's namespace along with the block's name identifier, separated by a colon and enclosed in double quotes.
#Example entry:
#"minecraft:gold_block" = "minecraft:stone"
#Warning, the same key cannot appear more than once in the replace map! For example, the following will cause an error:
#"minecraft:diamond_block" = "minecraft:stone"
#"minecraft:diamond_block" = "minecraft:air" 
[replace_map]
	"minecraft:diamond_block" = "minecraft:stone"
