#Disables File Watcher. Used to automatically update config if its file has been modified.
disableConfigWatcher = false
#Path to load default configs from, intended for setting global server configs for newly created worlds, but also works when recreating client and common configs.
defaultConfigsPath = "defaultconfigs"
