#Show a tooltip for the item currently selected in a container item's tooltip next to the main tooltip.
#Select a modifier key required to be held, otherwise selecting "KEY" serves as a toggle. The key is defined in vanilla's controls menu.
#Default Value: ALWAYS
#Allowed Values: KEY, ALWAYS, SHIFT, CONTROL, ALT
selected_item_tooltips = "ALWAYS"
#Invert scroll wheel direction for extracting / inserting items from a container item in precision mode.
#Default Value: false
invert_precision_mode_scrolling = false
#Color item inventories on tooltips according to the container item's color.
#Default Value: true
colorful_tooltips = true
#Select a modifier key required to be held to use precision mode.
#In precision mode left-clicking inserts an item, and right-clicking extracts a single item, overriding vanilla mouse interactions. The scroll wheel can also be used for quickly moving items.
#Default Value: CONTROL
#Allowed Values: SHIFT, CONTROL, ALT
precision_mode = "CONTROL"
#Expand container item tooltips to reveal their contents.
#Select a modifier key required to be held, otherwise selecting "KEY" serves as a toggle. The key is defined in vanilla's controls menu.
#Default Value: ALWAYS
#Allowed Values: KEY, ALWAYS, SHIFT, CONTROL, ALT
reveal_contents = "ALWAYS"
#Show an indicator on container items when the stack carried by the cursor can be added in your inventory.
#Default Value: true
container_item_indicator = true
#Always show item tooltips while interacting with container items, even when the cursor is currently carrying an item.
#Select a modifier key required to be held, otherwise selecting "KEY" serves as a toggle. The key is defined in vanilla's controls menu.
#Default Value: ALT
#Allowed Values: KEY, ALWAYS, SHIFT, CONTROL, ALT
carried_item_tooltips = "ALT"
#Disable sounds from inserting and extracting items from playing, as they trigger quite often with all the new interactions.
#Default Value: true
disable_interaction_sounds = true
#Render a white overlay or the hotbar selected item frame over the slot the next item will be taken out of when right-clicking the container item.
#Default Value: HOVER
#Allowed Values: HOTBAR, HOVER
slot_overlay = "HOVER"
