["Server Test"]
	#
	############################################
	#Enable this to show the unionlib config button in the main menu
	#-------------------------------------------
	#Default: true
	#-------------------------------------------
	"Boolean: Test Boolean 1" = true
	#
	############################################
	#Enable this to show the cape bestowed upon you if you are an obsidian supporter
	#-------------------------------------------
	#Default: true
	#-------------------------------------------
	"Boolean: Test Boolean 2" = true
